GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQnJ5YW4iLCJpYXQiOjE3MjE1NzYxNDYsImV4cCI6MTcyMTU3OTc0Nn0.ttCkTFsnGL20SYbVrzTGLdmA2wBZLyDjzPqK5BLnH8k

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
  "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQnJ5YW4iLCJpYXQiOjE3MjEwMzUxMTN9.JVQ1wf69eiG2F2AuHGxgO_DWw6LeLi679VxThJaPTMk"
}

###

POST http://localhost:4000/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQnJ5YW4iLCJpYXQiOjE3MjEwMzUxMTN9.JVQ1wf69eiG2F2AuHGxgO_DWw6LeLi679VxThJaPTMk"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
  "username": "Bryan"
}